//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ProdutoSpecs.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class ProdutoSpecs
{
	public Object description;
	public Object date_purch;
	public Object price_purch;
	public Object date_sale;
	public String getDescription()
	{
	
	}
	
	public Date getDate_purch()
	{
	
	}
	
	public Double getPrice_purch()
	{
	
	}
	
	public Date getDateSale()
	{
	
	}
}
