//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Subject.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class Subject
{
	public void registrarObserver(Object Observer o)
	{
	
	}
	
	public void removerObserver(Object Observer o)
	{
	
	}
	
	public void notificarPesquisaObserver(Object List resultado)
	{
	
	}
}
