//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Funcionario.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class Funcionario
{
	public void buscar()
	{
	
	}
}
