//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gerente.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class Gerente implements Funcionario
{
	private View view;
	private Model model;
	public void buscar()
	{
	
	}
	
	public void setV(Object View view)
	{
	
	}
}
