//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Observer.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class Observer implements Observer
{
	public void update(Object List l)
	{
	
	}
}
