//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerente.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class TelaGerente implements TelaGerente, Observer
{
}
