//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaCaixa.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class TelaCaixa implements Observer
{
	private Busca busca;
	private List produtos;
	public void update(Object List l)
	{
	
	}
}
