//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaAndroid.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class TelaAndroid implements Observer
{
	private Busca busca;
}
