//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaWeb.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class TelaWeb implements Observer
{
	private Busca busca;
}
