//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Estoque.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class Estoque implements Subject
{
	private List observer;
	private List produto;
	public void registrarObserver(Object Observer o)
	{
	
	}
	
	public void removerObserver(Object Observer o)
	{
	
	}
	
	public void NotificarPesquisaObserver(Object List resultado)
	{
	
	}
	
	public void addProduto(Object String name, Object String type, Object Double price_purch)
	{
	
	}
}
