//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Produto.java
//  @ Date : 20/03/2017
//  @ Author : 
//
//




public class Produto
{
	public Object name;
	public Object type;
	public Object price_sale;
	public String getName()
	{
	
	}
	
	public String getType()
	{
	
	}
	
	public Double getPrice_sale()
	{
	
	}
}
